[project]
name = "work-category-api-initial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SangerVithurshan", email = "159613760+Vithurshan2002@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "joblib>=1.6.0",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
work-category-api-initial = "work_category_api_initial:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
